### ISSUE TITLE
Implicit component names from sass/scss files starting with underscore

### ISSUE THREAD

**Issue by ivangretsky** [postcss/postcss-bem-linter#109]
Good day!

It is common to have scss partial names starting with underscore (like `_component.scss`). Unfortunately in that case it is impossible to use `implicitComponents` option, as the name of the component is determined from the filename (without extension) and is equal `_component` in this case.

I guess to fix it we should modify code around [this line](https://github.com/postcss/postcss-bem-linter/blob/master/index.js#L103) to get the underscore filtered out. 

I am not sure if the component in any notation can start with an underscore, but it could be wise to have an option to apply some regexp transformation to the filename (same way as we define `componentName` custom patterns) instead of making this hardcoded.

Can't yet solve this myself and produce a PR. Please help!

**Comment by simonsmith** [comment]
Fixed in #115
