### ISSUE TITLE
Are you open for another CSS preset?

### ISSUE THREAD

**Issue by redaxmedia** [postcss/postcss-bem-linter#110]
Hello,

before I put time into creating a preset for another [CSS naming convention](https://github.com/redaxmedia/ncss), I'd like to ask if this project is open for a pull request!?

Best regards
Henry

**Comment by simonsmith** [comment]
I think the intention is to keep it BEM focused. Does NCSS approach it a similar way?

cc @davidtheclark

**Comment by davidtheclark** [comment]
Yeah, I wouldn't be quick to add another tested, supported preset for a new system without as much traction yet — but @redaxmedia if you can come up with the regexps that work maybe we should put them in the README?

**Comment by redaxmedia** [comment]
No problem, I'll write up my own node module then. Don't worry...
