### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by layflags** [postcss/postcss-bem-linter#116]
The README section [Multiple definitions](https://bitbucket.shore.com/projects/FE/repos/app-shell/pull-requests/127/commits/7f311b84f3270146b0b49db2e713d60ed910ddba) gives the following examples:

```css
/* @define Foo */
.Foo {}

/* @define Bar */
.Bar {}

/* @define utilities */
.u-something {}
```
...
```css
/* @define Foo */
.Foo {}
/* @end */

.something-something-something {}
```

But shouldn't the comments start with `/**`? Single asterisk doesn't work for me, but this does:

```css
/** @define Foo */
.Foo {}

/** @define Bar */
.Bar {}

/** @define utilities */
.u-something {}
```
...
```css
/** @define Foo */
.Foo {}
/** @end */

.something-something-something {}
```

**Comment by simonsmith** [comment]
Good catch. Double checked the tests and you are correct. README updated
