### ISSUE TITLE
Please print expected selector in error message

### ISSUE THREAD

**Issue by AndyOGo** [postcss/postcss-bem-linter#123]
Currently it only tells me that `.foo` is invalid.

> 1:1  ✖  Invalid component selector ".foo"                      plugin/selector-bem-pattern

Though it would be awesome to instantly see the expected selector, like:

> 1:1  ✖  Invalid component selector ".foo" , expected ".bar"                    plugin/selector-bem-pattern

**Comment by simonsmith** [comment]
We could print the `componentName` which might be `bar` in this example but it's also possible that a regex might be used for something like namespaces and other complex combinations. For example from #130:

```js
^(\.(no|has|supports|t)-[a-z]+[-[a-z]+]*\s)?\.[co]-responsive-image(_{2}[a-z]+[-[a-z]+]*)?(-{2}[a-z]+[-[a-z]+]*)?(\.(is|has)-[a-z]+[-[a-z]+]*)?$
```

In this example the `componentName` is just `responsive-image` but it seems to be that alone would not be  very helpful for debugging. Printing the regex would also add to the confusion.

Happy to take suggestions but will close this for now.

**Comment by AndyOGo** [comment]
hmh, why is this closed?
