### ISSUE TITLE
Cannot get the plugin to log an error

### ISSUE THREAD

**Issue by jamesplease** [postcss/postcss-bem-linter#127]
I have a handful of CSS files that I would expect to error. One has the following class:

```css
.blah-plsPls__asdasd_--ad {
  color: #fff;
}
```

I'm using the following code, slightly modified from this project's README:

```js
'use strict';

const fs = require('fs');
const recursive = require('recursive-readdir');
const postcss = require('postcss');
const bemLinter = require('postcss-bem-linter');
const reporter = require('postcss-reporter');

recursive('client', ['!*.css'], (err, files) => {
  files.forEach(file => {
    const css = fs.readFileSync(file, 'utf-8');
    postcss()
      .use(bemLinter('bem'))
      .use(reporter())
      .process(css, { from: null });
  });
});
```

It's successfully grabbing all of the files (which I confirmed by adding `.then(results => console.log(results);`, but it never logs any warnings.

Am I missing something obvious here? 🙂 

Thanks for reading!

---

Versions:

postcss: 6.0.16
postcss-bem-linter 3.1.0
postcss-reporter 5.0.0

**Comment by simonsmith** [comment]
Does your css file have the `@define` comment at the top?

**Comment by simonsmith** [comment]
@jamesplease Did you find a resolution to this or would you need me to take another look?

**Comment by jamesplease** [comment]
I was never able to get this working, but I haven’t had a chance to try again. I’ll close this out for now. If I have the time to look into it again, and still face problems, I’ll reopen this.

thanks for the follow up!

**Comment by simonsmith** [comment]
Okay cool, sorry for the delay! 😄
