### ISSUE TITLE
How to configure it inside a postcss.config.js

### ISSUE THREAD

**Issue by tristanbes** [postcss/postcss-bem-linter#133]
Hello,

We're trying to cfg postcss-bem-linter inside a `postcss.config.js` but the documentation doesn't mention how to.

We've tried:

```js
module.exports = {
  plugins: {
    autoprefixer: {
      browsers: ["> 1%", "last 1 version", "not dead"]
    },
    bemLinter("bem")
  }
};
```

Without success (expceted identifyer).

**Comment by simonsmith** [comment]
That code snippet looks invalid to me. Would you not follow the `autoprefixer` example above?

```js
module.exports = {
  plugins: {
    autoprefixer: {
      browsers: ["> 1%", "last 1 version", "not dead"]
    },
    'postcss-bem-linter': { /* options */ }
  }
};
```

Documentation here - https://github.com/michael-ciniawsky/postcss-load-config

**Comment by tristanbes** [comment]
thanks for the hint.

I've put

```js
module.exports = {
  plugins: {
    autoprefixer: {
      browsers: ["> 1%", "last 1 version", "not dead"]
    },
    'postcss-bem-linter': { preset: "bem" },
  }
};
``` 

At this point, I can't confirm it's working, but at least it doesn't give me a parsing error :S

**Comment by simonsmith** [comment]
Closing as no further discussion
