### ISSUE TITLE
Ability to have a themed component

### ISSUE THREAD

**Issue by maxhartshorn** [postcss/postcss-bem-linter#142]
There is a use case for having multiple versions of a component, built off the same component: [see here](http://getbem.com/faq/#can-a-block-modifier-affect-elements-)

A real world example would be a site search form with a full-width variant.

```
<form class="site-search  site-search--full">
    <input type="text" class="site-search__field">
    <input type="Submit" value ="Search" class="site-search__button">
</form>
```

It would be great to be able to define a component like: `site-search--full`, however if we define a component as such, the following selector would be invalid:

```
.site-search--full .site-search__field {
    color: #000;
}
```

Since the component is defined as `.site-search--full` it expects the second selector to be `.site-search--full__field`. However enforcing this standard would unnecessarily complicate markup:

```
<form class="site-search  site-search--full">
    <input type="text" class="site-search__field site-search--full__field">
    <input type="Submit" value ="Search" class="site-search__button site-search--full__button">
</form>
```

I realize this could be fixed with weak mode, but that isn't ideal. What would be great is to be able to have a selector like this appear as valid:

`.site-search--full .site-search__field`

And a selector like this fail:

`.site-search--full .other-component`

Is there a way to do this currently with the tool? Do you feel it would be a useful feature?

**Comment by simonsmith** [comment]
If add the following to `bem-valid.css` (a fixture file in the tests) it passes:

```css
.block-name--mod .block-name__elem {}
```

Do you have a reproducible example of this failing?

**Comment by maxhartshorn** [comment]
To be more specific. This error occurs when using `implicitComponents`

1. I create a scss partial named `_block-name--mod`
2. The file contains a rule along the lines of `.block-name--mod .block-name__elem {}`

This will produce the error. Noticing now that it can be fixed by adding a `/** @define block-name */`. But it would be convenient if this step wasn't necessary, as it could through newer devs on a shared project for a loop.

**Comment by simonsmith** [comment]
> I create a scss partial named _block-name--mod

Is this a standard BEM practice? I would always expect the component filename to be `_block-name.scss` and then any modifiers would live within it. I would also predict this would work correctly with `implicitComponents` as well.

**Comment by maxhartshorn** [comment]
It may not be standard practice but I have seen it used in projects. It helps if you have a large number of mods for a component.

**Comment by simonsmith** [comment]
I don't think there is a change to make here. This is quite an edge case use of `implicitComponents` from my experience and can be worked round by using `@define` as you mentioned.
