### ISSUE TITLE
move to postcss org

### ISSUE THREAD

**Issue by necolas** [postcss/postcss-bem-linter#49]
@ai would you be ok with this repo moving into the postcss org?

**Comment by MoOx** [comment]
I am :)
Do you want to add new collaborators ?

**Comment by ai** [comment]
Twitter's project in PostCSS officially :-). Sure

**Comment by necolas** [comment]
ok done. feel free to add any collaborators you want

**Comment by necolas** [comment]
and fwiw, i am not opposed to changes like making 'bem' the default rather than 'suit'. please consider this as a postcss community project now.
