### ISSUE TITLE
working with postcss-cli

### ISSUE THREAD

**Issue by VinSpee** [postcss/postcss-bem-linter#55]
Is this configuration compatible with postcss-cli? It seems as though it's not. when doing:

```bash
postcss --use postcss-bem-linter --postcss-bem-linter.namespace "br" ./src/styles/main.css
```

I'm getting the error 
```bash
[TypeError: Cannot read property 'initial' of undefined]
```

I assume it's because of this's plugin's unusual configuration signature - any thoughts?

**Comment by davidtheclark** [comment]
What's unusual about the signature? Is it that there are two arguments instead of just one object?

**Comment by VinSpee** [comment]
yes, that's what I am referring to. What are your thoughts on it?

**Comment by davidtheclark** [comment]
I guess I don't see a reason not to merge those two arguments into one big options object except that it would mean a breaking change. I haven't looked into `postcss-cli` yet --- I'll take a gander.

**Comment by VinSpee** [comment]
Yeah that's my worry too. Seems like a waste to do a 2.0 when you're just
moving an argument. Then again, it might be worth it to follow
"convention"-ish? And versions are free.

**Comment by VinSpee** [comment]
looks like it's in the [postcss plugin guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#14-create-plugin-by-postcssplugin)

**Comment by davidtheclark** [comment]
We're using the plugin function here, so I don't think it's violating the guidelines.

I try to look into this and the CLI this weekend sometime.

**Comment by davidtheclark** [comment]
Sorry I've been dilatory on the update, @VinSpee. Here's what I'm thinking: I want to make some other breaking changes to the API -- leaving the `:root` checking stuff to `stylelint`. But I wanted to wait until https://github.com/stylelint/stylelint/issues/133 is taken care of. I'd then work this breaking change into the same release. Seem good?

**Comment by VinSpee** [comment]
Makes great sense - thanks

**Comment by davidtheclark** [comment]
@VinSpee: I thought some more about this and left a comment in `postcss-cli`: https://github.com/code42day/postcss-cli/issues/21#issuecomment-127816623

I'm not very inclined to shape the API to accommodate the limitations of `postcss-cli`'s `--plugin.option` format. If we think of an arrangement that seems better for its own sake, though, sure.

**Comment by davidtheclark** [comment]
What do you think of this possible accommodation?

```md
You can use a preset pattern and its options in two ways:
- pass the preset's name as the `pattern`, and, if needed, an `options` object,
e.g. `bemLinter('suit', { namespace: 'twt' })`.
- pass an object as `pattern`, with the preset's name as the `preset` property and that preset's options as other properties, e.g. `bemLinter({ preset: 'suit', namespace: 'twt' })`.
```

**Comment by davidtheclark** [comment]
Any @postcss/owners have opinions about this kind of function signature business and whether/how to accommodate `postcss-cli`?

**Comment by davidtheclark** [comment]
Or another possibility: `bemLinter({ preset: 'suit', presetOptions: { namespace: 'twt' }})`

**Comment by davidtheclark** [comment]
Just released 0.5.0 allowing for that last idea: `bemLinter({ preset: 'suit', presetOptions: { namespace: 'twt' }})`

**Comment by VinSpee** [comment]
👌🏼Thanks!

**Comment by ben-eb** [comment]
@davidtheclark Late to the party but yeah, `0.5.0` lgtm. :+1:
