### ISSUE TITLE
Outsource :root-related checks to stylelint

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-bem-linter#56]
stylelint has rules in place to check the two things that this linter currently checks (only custom properties in `:root` rules; `:root` cannot be combined with other selectors). So I figure this plugin may as well focus on its unique contribution --- checking selectors against dynamic regular expressions that know about component names --- and outsource that other business.

This would be a breaking change, of course.

**Comment by jeddy3** [comment]
Sgtm.

**Comment by simonsmith** [comment]
Hey, with regard to the removal of:

    The `:root` cannot be combined with other selectors.

Does such a rule for stylelint exist? Wanted to check before I look into adding it.

Also thinking about validating the custom property after the componentName to ensure it is camel case, as per this issue - https://github.com/suitcss/suit/issues/91

It would cross over closely with the validation already perform by the bem-linter. Any thoughts on where that responsibility should lie?

**Comment by davidtheclark** [comment]
selector-root-no-composition --- https://github.com/stylelint/stylelint/tree/master/src/rules/selector-root-no-composition

If camelcase custom property names is a SUIT convention that you want to enforce, I'd say we should build it into this module as part of the SUIT preset. We would also want to add a new option so the user could specify a patternf ro custom property validation.

**Comment by simonsmith** [comment]
Great, thanks

Still need to update the SUIT components and documentation. Will open an issue nearer the time.
