### ISSUE TITLE
Maybe coming up on 1.0.0?

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-bem-linter#58]
After pruning out the `:root`-selector checks (outsourcing them to stylelint), I think that this module is pretty focused: check selectors against regular expressions that are tailored by a special comment. 

I don't see any bugs reported since May 11, so there's a good chance this means the intended functionality is working well for users.

Maybe that means we should have a 1.0.0 release. 

My only hesitation is that I wonder whether other people think the API is unclear or weird or they have better ideas. If not, I think 1.0.0 release should come soon, probably after #57.

**Comment by jeddy3** [comment]
> Maybe that means we should have a 1.0.0 release.

Sgtm! This is a solid tool. Thanks for all your additions to the tool since you took over the reins of it. It's very much appreciated :) I've been using it to enforce the suitcss conventions for over a year now, and it's worked out great.

**Comment by davidtheclark** [comment]
Breaking changes for PostCSS 5.0 was good enough reason to make the bump. 1.0.0 is out now, compatible with PostCSS 5.

**Comment by jeddy3** [comment]
Thanks for this! :)
