### ISSUE TITLE
Atom editor plugin

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-bem-linter#62]
That would be really nice.

**Comment by vincentorback** [comment]
Definitely! Maybe a plugin for the existing [linter-stylelint](https://github.com/AtomLinter/linter-stylelint) or maybe we would need a new plugin UI for Atom to make it as flexible for the options in this postcss-plugin.

**Comment by davidtheclark** [comment]
The new goal is to avoid needing to do this by building a stylelint plugin, so users can get their Atom inline linting via linter-stylelint: https://github.com/davidtheclark/stylelint-selector-bem-pattern
