### ISSUE TITLE
Settings for ignoring specific selectors

### ISSUE THREAD

**Issue by vincentorback** [postcss/postcss-bem-linter#63]
Would love an additional regex selector for ignoring classes like `html.no-flexbox` or `html.is-loaded` and other smaller state classes or _fixes_. Using `/* postcss-bem-linter: ignore */` works but it can get messy fast with to many. Also it would be nice to keep gulp-plugins out of the code.

Does this sound like something usable to y'all? :rocket:

**Comment by tornqvist** [comment]
:+1:

**Comment by davidtheclark** [comment]
That sounds reasonable to me. So as a peer to `componentSelectors` and `utilitySelectors` we'd have `ignoredSelectors`, right?

> Also it would be nice to keep gulp-plugins out of the code.

I don't understand that part; could you clarify?

**Comment by vincentorback** [comment]
Yeah exactly that would be sweet! But specifying every single possible Modernizr class (or whatever it is) might be a bit of a hassle, so maybe more of a flexible regex pattern. So that you can specify to ignore `.has-` classes, or selectors beginning with `html` or whatever. Or do you think that might be too flexible and hard to setup?

--

> Also it would be nice to keep gulp-plugins out of the code.

By this I just mean that I think it’s nice to keep your CSS files clean from whatever building tool you’re using. Making it easier to refactor and jump around between processors.

**Comment by davidtheclark** [comment]
Ah, so you don't link the plugins-specific comments. I see.

I agree that `ignoredSelectors` should be a regex.

I'm open to a PR on this or will try to get around to it soon.

**Comment by davidtheclark** [comment]
Released in 1.1.0: https://github.com/postcss/postcss-bem-linter#custom-patterns

**Comment by vincentorback** [comment]
Sweeet!
