### ISSUE TITLE
Compatibility SASS nested rules?

### ISSUE THREAD

**Issue by KingScooty** [postcss/postcss-bem-linter#77]
I'm currently doing a spike to see how well this plugin fits in with our current development pipeline. I've currently got it running with PostCSS, Stylelint, and PostCSS-SCSS (to allow PostCSS to work with SASS files).

This plugin is working pretty nicely with SASS formatted CSS, but there are a few quirks. Ideally, i'd like to lint these files without having to compile/process them into raw CSS. The following scenario below demonstrates an issue where a selector nested inside another selector results in a BEM selector error.

Is this something that could be accommodated, or is it outside the scope of this project? It would be incredible if this was supported. 

```sass
.gs-c-item-status--live {
    text-transform: uppercase;
    font-weight: bold;

    @include theme('sport') {
        color: $sp-c-live-blue;
    }

    @include theme('news') {
        color: $nw-c-red;
    }

    &.gs-c-item-status--on-dark {
        @include theme('sport') {
            color: $sp-c-live-blue-on-dark;
        }
    }
}
```

Error reported:

```sh
[14:14:45] Starting 'sass-lint'...

app/assets/_scss/components/_item-status.scss
25:5	⚠  Invalid component selector "&.gs-c-item-status--on-dark" (selector-bem-pattern) [stylelint]

[14:14:45] Finished 'sass-lint' after 520 ms
```

**Comment by davidtheclark** [comment]
Couldn't you adjust your regex to accommodate `&` symbols?

**Comment by davidtheclark** [comment]
It does seem weird to me, though, that you are nesting in that way. It would make sense to me nesting state classes; but aren't you right now combining two modifiers? `.gs-c-item-status--live.gs-c-item-status--on-dark` I think you would have cleaner selector specificity if you created a single modifier class that does what you need in that situation.

**Comment by KingScooty** [comment]
Hmm, in some situations that would work, but there are so many scenarios and states that need to be accounted for in this codebase, that we actually use the increased specificity to enforce the rule in certain situations like the one above where another modifier may clash.

**Comment by KingScooty** [comment]
The following seems to be doing the job :+1: 

```js
        componentSelectors: function(componentName) {
          var WORD = '[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*';
          var ampersand = '(?:\&)*';
          var element = '(?:__' + WORD + ')?';
          var modifier = '(?:--' + WORD + '){0,2}';
          var attribute = '(?:\\[.+\\])?';

          regex = '^' + ampersand + '\\.' + componentName + element + modifier + attribute + '$';
          return new RegExp(regex);
        }
```

**Comment by dryoma** [comment]
Sorry, but I would like to bring this up again. We too have a pipeline that includes sass compiling, and are going to adobt a BEM-like naming convention. Though the nesting example above could be unnecessary, the ones like these:
```
.MyComponent {
    &.isStateName { ... }
    .itemName { ... }
}
```
seem to be unavoidable. Yet, postcss-bem-linter (as of version 2.4.1) throws on both, even with weak mode enabled.

There sure are workarounds requiring some customizing, but they have their downfalls:

* defining one's own patterns kind of kills the charm of having a preset;
* using other PostCSS plugins like `postcss-bem-linter` from the other issue would require separate pipelint, and produce CSS and so selector names and line numbers in error output will be incorrect.

So I'd agree with the author in that it would be great to have nesting in built-in patterns.

**Comment by davidtheclark** [comment]
The thing is, that preset is for SUITCSS and we want to make it fit that methodology strictly. So @simonsmith, @giuseppeg, @timkelty, do you want to allow for nesting in SUITCSS?

If they don't, then a new pattern is needed for what you're doing, @dryoma. If you or @KingScooty or anybody else wants to PR a new preset that others can benefit from, that would be fantastic.

**Comment by simonsmith** [comment]
I have to admit, I do use `postcss-nested` for things like state classes and `hover`, `focus` etc.

**Comment by davidtheclark** [comment]
Ok, I can reopen this. Open to a PR.

**Comment by giuseppeg** [comment]
Maybe we can allow only the following:
```css
.Block {
  &.is-stateName {}
  &-element {}
  &-element--modifier {}
  &--modifier {}
  &:pseudo-class {}
  &:pseudo-element {}
  &::pseudo-element {}
  &[attr] {}
}
```

**Comment by dryoma** [comment]
Thanks everyone for considering this feature!

As for `&-element {}` - the con is that if `&` is a part of a classname, the resulting class can't be found with a search (it just doesn't esixt in the code).

**Comment by simonsmith** [comment]
> Open to a PR

@davidtheclark Happy to have a look at this. Been wanting to dive into the source of this project for a while
