### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by dikmax** [postcss/postcss-bem-linter#80]
Linter crashes on start with following exception:

```
TypeError: Cannot read property 'start' of undefined
    at /Users/dikmax/workspace/redesign/node_modules/postcss-bem-linter/index.js:40:38
    at /Users/dikmax/workspace/redesign/node_modules/postcss/lib/container.js:110:28
    at /Users/dikmax/workspace/redesign/node_modules/postcss/lib/container.js:73:26
    at AtRule.each (/Users/dikmax/workspace/redesign/node_modules/postcss/lib/container.js:60:22)
    at AtRule.walk (/Users/dikmax/workspace/redesign/node_modules/postcss/lib/container.js:72:21)
    at /Users/dikmax/workspace/redesign/node_modules/postcss/lib/container.js:75:32
    at Root.each (/Users/dikmax/workspace/redesign/node_modules/postcss/lib/container.js:60:22)
    at Root.walk (/Users/dikmax/workspace/redesign/node_modules/postcss/lib/container.js:72:21)
    at Root.walkRules (/Users/dikmax/workspace/redesign/node_modules/postcss/lib/container.js:108:25)
    at /Users/dikmax/workspace/redesign/node_modules/postcss-bem-linter/index.js:37:10
```

I've tried with both gulp and postcss-cli.

postcss@5.0.16

**Comment by davidtheclark** [comment]
Can you please provide more information about your build?

The line throwing this error is `var ruleStartLine = rule.source.start.line;`. So for some reason your code is not getting a `source` ascribed to it. That makes me wonder if there's something wrong if you PostCSS configuration. Maybe?

**Comment by dikmax** [comment]
I'm trying build with postcss-cli with this config (postcss.json):

```json
{
    "use": [
        "postcss-import",
        "postcss-mixins",
        "postcss-cssnext",
        "lost",
        "postcss-responsive-type",
        "postcss-quantity-queries",
        "postcss-short",
        "postcss-bem",
        "postcss-nested",
        "postcss-bem-linter"
    ],
    "cssnext": {
        "browsers": "> 5%",
        "compress": false
    },
    "postcss-bem-linter": {
        "preset": "bem"
    },
    "postcss-bem": {
        "style": "bem",
        "shortcuts": {
            "component": "b",
            "descendent": "e",
            "modifier": "m"
        }
    }
}
```

Without "postcss-bem-linter" line it works pretty fine.

**Comment by davidtheclark** [comment]
@dikmax: I will write a fix so the plugin doesn't throw an error when nodes do not have sources.

You should be aware, though, that this means on of the plugins you're using is probably creating nodes without source attributes and therefore positions in sourcemaps, error reports, etc., on those nodes won't be wholly accurate. If you feel like investigating which plugin is doing it, I'm sure the author would fix the problem.

For reference, in [the PostCSS API docs](https://github.com/postcss/postcss/blob/master/docs/api.md#nodesource) it says:

> If you create a node manually (e.g., with postcss.decl()), that node will not have a source property and will be absent from the source map. For this reason, the plugin developer should consider cloning nodes to create new ones (in which case the new node’s source will reference the original, cloned node) or setting the source property manually.

**Comment by davidtheclark** [comment]
Published fix in 2.3.2

**Comment by davidtheclark** [comment]
I just realized that solution is flawed. We really need to ignore any nodes that do not have sources, because without the source positions we can't determine whether the node is supposed to fit a certain "component" or not. I will adjust a publish a new version ...

**Comment by davidtheclark** [comment]
Ok. In 2.3.3 any nodes that lack source properties should be ignored.

@dikmax Please let me know how this works for you when you have a chance to try it out.

**Comment by dikmax** [comment]
Thanks for help.

It doesn't crash now. But doesn't show any lint error either, probably because lot of code is ignored.

That is actually strange. For testing purposes I left only postcss-bem-linter and reporter plugins. It shows no errors on following file:

```css
#just .for #testing .purposes {
    color: black;
}
```

I run it using 

```bash
node_modules/.bin/postcss -c postcss.json styles/styles.pcss
```

config:

```
{
    "use": [
        "postcss-bem-linter",
        "postcss-reporter"
    ],
    "postcss-bem-linter": {
        "preset": "bem"
    }
}
```

**Comment by davidtheclark** [comment]
@dikmax Can you try with a different PostCSS runner (not postcss-cli)? If it works with another runner, we'd know the problem was with postcss-cli.

**Comment by dikmax** [comment]
I've tried with gulp, same thing.

gulpfile.js:

```js
var gulp = require('gulp');
var rename = require('gulp-rename');
var postcss = require('gulp-postcss');
var reporter = require('postcss-reporter');
var bemLinter = require('postcss-bem-linter');

var paths = {
    styles: 'styles/*.pcss'
};

gulp.task('styles', function () {
    var processors = [
        bemLinter({
            "preset": "bem"
        }),
        reporter()
    ];
    return gulp.src('styles/styles.pcss')
        .pipe(postcss(processors))
        .pipe(rename({
            extname: '.css'
        }))
        .pipe(gulp.dest('css'));
});

gulp.task('watch', function() {
    gulp.watch(paths.styles, ['styles']);
});

gulp.task('default', ['watch', 'styles']);
```

Look like it's problem with bem-linter itself.

**Comment by dikmax** [comment]
I've tried to replace linter with some other tool that shows warnings, colorguard. And it shows warnings as expected on same configuration.

**Comment by davidtheclark** [comment]
You say you tested on the following file:

```css
#just .for #testing .purposes {
    color: black;
}
```

That file in fact should *not* log any warnings because it does not have a component definition at the top. 

I just verified that the following *does* work as expected:

```css
/** @define foo */

#just .for #testing .purposes {
    color: black;
}
```
