### ISSUE TITLE
Support for linting BEM selectors without component definition?

### ISSUE THREAD

**Issue by bookwyrm** [postcss/postcss-bem-linter#82]
**Background:** 
I have an existing project using [scss-lint](https://github.com/brigade/scss-lint) which I'm migrating to [stylelint](http://stylelint.io) for faster performance. One of the things I want to lint is selector format in which I'm following the [Harry Roberts convention](https://en.bem.info/tools/bem/bem-naming/#convention-by-harry-roberts) (originally described [here](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/))

**The Ask:**
The way that `postcss-bem-linter` is written, it requires a "component definition" in order for the linter to check anything. My concern is that this represents an opt-in scenario for developers. If they never setup a component definition then their selectors will never be linted.

*Using `postcss-bem-linter`, is it possible to just check that all selectors conform to the general pattern for naming (`block__element--modifier`) according to the convention above but without a component definition?*

**The Followup:**
Where does this concept of a "component definition" come from? I haven't been able to find any documentation on its use with BEM apart from the [`postcss-bem-linter` README](https://github.com/postcss/postcss-bem-linter#defining-a-component).

**Comment by davidtheclark** [comment]
> My concern is that this represents an opt-in scenario for developers. If they never setup a component definition then their selectors will never be linted.

That's true. The current way around that would be manual code review. But it's possible that we could add an option to issue a warning if files with certain paths do not start with a component definition. What do you think of that?

The component definition is what makes this linter unique, I think. If you don't want to use component definitions, you should be able to accomplish what you're after with stylelint's [selector-class-pattern](http://stylelint.io/user-guide/rules/selector-class-pattern/) rule, which just checks every class against a regexp. (So to answer your exact question: no it's not possible with postcss-bem-linter, but it is possible with stylelint.)

In fact, if you're worried about devs opting out, maybe you want to use both rules in tandem: if a dev leaves out the definition, her classes are still checked against selector-class-pattern; and if the dev does include the definition, her classes are checked against postcss-bem-linter.

What do you think?

**Comment by bookwyrm** [comment]
@davidtheclark Thanks for the quick response. I think that your suggestion is a good one - I overlooked `selector-class-pattern` when I found your [stylelint-selector-bem-pattern](https://github.com/davidtheclark/stylelint-selector-bem-pattern).

I added a rule:
```
    "selector-class-pattern": "^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$",
```

It's petty gnarly but it works.

For now though I'm going to shelve the migration to stylelint as it isn't as feature-rich as scss-lint. The main things I've come across that I'm missing are:
* [ColorVariable](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorvariable)
* [DeclarationOrder](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#declarationorder)
* [Indentation](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#indentation) - with support for visual hints of hierarchy

I'll see about adding plugins to stylelint for the above features as I have time.

**Comment by davidtheclark** [comment]
> isn't as feature-rich as scss-lint

Bold statement, and probably false, gotta say --- but I understand that it may not have some particular features that you want, especially SCSS-specific ones.

Feel free to log issues for rule requests at stylelint. Just to address the ones you brought up:

- ColorVariable is SCSS-specific, so yeah probably needs to be an external plugin (you may want to look into [stylelint-scss](https://github.com/kristerkari/stylelint-scss) which @kristerkari is trying to get started.
- Same with DeclarationOrder.
- Indentation is supported, but BEM-style hierarchy is not, as you say. That request has come up before and we decided it should be a third-party plugin because it's so methodology-specific.

Thanks for the details!

**Comment by bookwyrm** [comment]
> Bold statement, and probably false, gotta say --- but I understand that it may not have some particular features that you want, especially SCSS-specific ones.

Apologies for the statement. You are absolutely right. It doesn't have the specific features that I want but in general stylelint looks very feature-rich and capable.

I'll check out stylelint-scss

**Comment by jitendravyas** [comment]
@bookwyrm Is it for Harry potter's BEM style?

`"selector-class-pattern": "^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$",`
