### ISSUE TITLE
'Hyphenated BEM' regex not behaving as expected

### ISSUE THREAD

**Issue by davidpmccormick** [postcss/postcss-bem-linter#89]
I'm trying to emulate the 'hyphenated BEM' selector format from [scss-lint](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#selectorformat), but the regex I've got doesn't work in the context of the plugin (I'm fairly sure the regex itself is sound – it behaves as expected if I run it through [e.g. regexper](https://regexper.com/#%5C.%7BcomponentName%7D(((__%7C--)((%5Ba-z0-9%5D%2B(%3F!-%24)-%3F)%2B))%2B)%3F)

Here's my `componentSelectors` property:

    "componentSelectors": {
      "initial": "^\\.{componentName}(((__|--)(([a-z0-9]+(?!-$)-?)+))+)?"
    }

If I've defined a `article-intro`, then I would expect e.g. `article-intro__heading` or `article-intro--primary` to  be good matches, and `article-intro-_` to be an error, but the linter isn't currently complaining at all about `.article-intro-_`. Any ideas?

**Comment by davidpmccormick** [comment]
Ignore me – not only did I intent to post this on the [Atom plugin](https://github.com/davidtheclark/stylelint-selector-bem-pattern) issues, it appears my problems are solved by adding a `$` to the end of my regex.

**Comment by karmasalad** [comment]
@davidpmccormick Can you share your configuration setup for hyphenated BEM selector format? I'm having trouble getting it to work the same as it does in scss-lint.

**Comment by davidpmccormick** [comment]
@karmasalad I've written up what I'm currently going with, here: http://www.sumnoise.com/2016/05/26/stylelint-hyphenated-bem-config/

**Comment by coreybruyere** [comment]
Ok, ignore my last comment. It wasn't bem-linter giving me that error. I'm extending another config with a rule assigned to "selector-class-pattern". I used this to override that rule:
`"selector-class-pattern": "^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$"`
