### ISSUE TITLE
Linting without /** @define ... */

### ISSUE THREAD

**Issue by timkraut** [postcss/postcss-bem-linter#92]
Hi,

I was wondering if there is any way to lint components without annotating them with `/** @define ... */`? I use a separate file for every component and would like to make sure that all names stick to the correct pattern (BEM in my case).

Thanks!

**Comment by simonsmith** [comment]
It's a good idea and has been raised in #88. We should probably continue that discussion and work out how it will function.

**Comment by timkraut** [comment]
@simonsmith Thanks for pointing to this issue. I haven't found it. I'll close this one.
